os: linux
dist: xenial
language: python
jobs:
  include:
    - name: "Django tests excludling selenium"
      language: python
      python: 3.6
      before_install:
        # Move source code to a directory structure the application expects.
        - mkdir -p lib/test/src/temmpo
        - shopt -s extglob
        - mv !(lib) lib/test/src/temmpo/
        - cd lib/test/src/temmpo/temmpo/settings/
        - ln -s travis_ci_private_settings.py private_settings.py
        - pwd
        - ls
        - cd $TRAVIS_BUILD_DIR
        - mkdir -p var/abstracts
        - mkdir -p var/data
        - mkdir -p var/log
        - mkdir -p var/results/testing/v1
        - mkdir -p var/results/testing/v3
        - mkdir -p var/results/testing/v4
        - mkdir -p var/tmp
      install:
        - cd $TRAVIS_BUILD_DIR
        - cd lib/test/src/temmpo
        - pip3 install -U pip==20.3.3
        - pip3 install setuptools==50.3.2
        - pip3 install pip-tools==5.4.0
        - pip3 freeze
        - pip3 install -r requirements/requirements.txt
        - pip-sync requirements/test.txt
      services:
        - mysql
        - redis
      script:
        - cd $TRAVIS_BUILD_DIR
        - cd lib/test/src/temmpo
        - coverage
        - coverage run --source='.' manage.py test --settings=temmpo.settings.test_mysql --exclude-tag=selenium-test --exclude-tag=slow
        - coverage report --skip-empty --skip-covered -m
        - coverage run --source='.' manage.py test --settings=temmpo.settings.test_mysql --exclude-tag=selenium-test --tag=slow
        - coverage report --skip-empty --skip-covered -m
    - name: "Syntax check Python 2 Fabric deployment script"
      language: python
      python: 2.7
      script:
        - pip install fabric==1.13.1
        - fab -l -f deploy/fabfile.py
        # NB: When deployed Fabric is installed at a system packages level and supports the CI/CD pipeline
branches:
  only:
  - master
  - /^TMMA-.*$/
