language: python

python:
  - '2.7'

before_install:
  # Move source code to a directory structure the application expects.
  - mkdir -p lib/test/src/temmpo
  - shopt -s extglob
  - mv !(lib) lib/test/src/temmpo/
  - cd lib/test/src/temmpo/temmpo/settings/
  - ln -s travis_ci_private_settings.py private_settings.py
  - pwd
  - ls
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p var/abstracts
  - mkdir -p var/data
  - mkdir -p var/log
  - mkdir -p var/results/testing/v1
  - mkdir -p var/results/testing/v3

install:
  - cd $TRAVIS_BUILD_DIR
  - cd lib/test/src/temmpo
  - pip install -U pip==19.1.1
  - pip install -U setuptools==44.1.0
  - pip install pip-tools==4.5.1
  - pip freeze
  - pip install -r requirements/requirements.txt
  - pip-sync requirements/test.txt

services:
  - mysql
  - redis-server

script:
  - cd $TRAVIS_BUILD_DIR
  - cd lib/test/src/temmpo
  - coverage run --source='.' manage.py test --settings=temmpo.settings.test_mysql --exclude-tag=selenium-test
  - coverage report --skip-empty --skip-covered -m
  # NB: When deployed Fabric is installed at a system packages level and supports the CI/CD pipeline
  - pip install fabric==1.13.1
  - fab -l -f deploy/fabfile.py

after_success:
  # Update requirements third party dependenacy checking service
  - test $TRAVIS_BRANCH = "TMMA-93" && requires.io update-branch -t $REQUIRES_IO_TOKEN -r rit/temmpo -n $TRAVIS_BRANCH requirements/

branches:
  only:
  - master
  - /^TMMA-.*$/
