image: centos/python-27-centos7:2.7

pipelines:
  branches:
    '{TMMA-*,master}':
    - step:
        script:
          - pip install -U pip==9.0.3
          - pip install -r requirements/base.txt
          - pip-sync requirements/base.txt
          - mkdir -p /opt/var/results
          - mkdir -p /opt/var/abstracts
          - mkdir -p /opt/var/data
          - mkdir -p /opt/var/log
          - ln -s /opt/atlassian/pipelines/agent/build/temmpo/settings/bitbucket_pipelines_private_settings.py /opt/atlassian/pipelines/agent/build/temmpo/settings/private_settings.py
          - python manage.py test --settings=temmpo.settings.test_sqlite
