image: centos:7.6.1810

pipelines:
  branches:
    '{TMMA-*,master}':
    - step:
        caches:
          - pip
        script:
          # Put source code where build scripts expect
          - mkdir -p /usr/local/projects/temmpo/lib/dev/src/temmpo
          - cp -r . /usr/local/projects/temmpo/lib/dev/src/temmpo
          - ls /usr/local/projects/temmpo/src/temmpo
          # Run development set up scripts which mimics puppet additions in test, demo and production HyperV VMs
          - sh /usr/local/projects/temmpo/lib/dev/src/temmpo/deploy/deploy-centos.sh
          - fab -V
          # Run the development version of the Fabric build scripts
          - fab make_virtualenv:env=dev,configure_apache=False,clone_repo=False,branch=None,migrate_db=True,use_local_mode=True,requirements=dev -f /usr/local/projects/temmpo/lib/dev/src/temmpo/deploy/fabfile.py
          # Run tests including those using a headless browser
          - cd /usr/local/projects/temmpo/lib/dev/bin && source activate && cd /usr/local/projects/temmpo/lib/dev/src/temmpo
          - python -v
          - python manage.py test --settings=temmpo.settings.test_sqlite
