image: centos:7.6.1810

pipelines:
  branches:
    '{TMMA-*,master}':
    - step:
        caches:
          - pip
        script:
          - yum -y install epel-release
          - yum -y update
          - yum -y install python-devel
          - yum -y install python-wheel
          - yum -y install python-magic
          - yum -y install python-pip
          - yum -y install python-virtualenv
          - yum -y install libxml2-python
          - yum -y install libxml2-devel
          - yum -y install libxslt-python
          - yum -y install libxslt-devel
          - yum -y install python-lxml
          - yum -y install gcc gcc-c++
          - yum -y install wget
          - yum -y install mariadb
          - yum -y install mariadb-devel
          - yum -y install mysql-devel
          - yum -y install mysql-connector-python
          - yum -y install mysql-utilities
          - wget https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
          - yum -y localinstall mysql57-community-release-el7-11.noarch.rpm
          - yum -y install mysql-community-libs
          - yum -y install mysql-community-client
          - yum list installed
          - pip install virtualenv
          - virtualenv venv
          - ./venv/bin/pip install -U pip==19.1.1
          - ./venv/bin/pip install -U pip-tools==3.7.0
          - ./venv/bin/pip install -U setuptools==41.0.1
          - ./venv/bin/pip freeze
          - ./venv/bin/pip install -r requirements/test.txt
          - ./venv/bin/pip-sync requirements/test.txt
          - mkdir -p /opt/var/results/testing/v1
          - mkdir -p /opt/var/results/testing/v3
          - mkdir -p /opt/var/abstracts
          - mkdir -p /opt/var/data
          - mkdir -p /opt/var/log
          - ln -s /opt/atlassian/pipelines/agent/build/temmpo/settings/bitbucket_pipelines_private_settings.py /opt/atlassian/pipelines/agent/build/temmpo/settings/private_settings.py
          - ./venv/bin/python manage.py test --settings=temmpo.settings.test_mysql --exclude-tag=selenium-test
          - pip install fabric==1.13.1
          - fab -l -f deploy/fabfile.py
        services:
          - redis
          - mysql
definitions:
  services:
    redis:
      image: redis:5.0.5
    mysql:
      image: mysql:5.6.44
      variables:
        MYSQL_DATABASE: 'pipelines'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USERNAME: 'test_user'
        MYSQL_PASSWORD: 'test_user_password'