image: python:2.7.13

pipelines:
  default:
    - step:
        script:
          - pip install -U pip==9.0.1
          - pip install -r requirements/base.txt
          - mkdir -p /opt/atlassian/pipelines/var/results
          - mkdir -p /opt/atlassian/pipelines/var/abstracts
          - mkdir -p /opt/var/log
          - python manage.py test
