version: '3'

services:
  web:
    hostname: dev.temmpo.org.uk
    build:
      context: ./web/
      args:
        REQUIREMENTS_FILE: dev.txt
    links:
      - mysql:mysql
    ports:
      - "8000:8000"
      # TODO review usage of passing in correct ---settings file for the env.
    command: bash -c "/srv/temmpo/bin/python manage.py collectstatic --noinput && /srv/temmpo/bin/python manage.py migrate && /srv/temmpo/bin/python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./web:/srv/temmpo/src/temmpo/
    depends_on:
      - mysql

  nginx:
    volumes:
      - ./nginx/certs:/etc/pki/tls/certs/:ro
      - ./nginx/private:/etc/pki/tls/private/:ro

  mysql:
    restart: always
    image: mysql:8
    ports:
      - "4406:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    env_file: .env
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p$MYSQL_ROOT_PASSWORD"]
      timeout: 45s
      interval: 10s
      retries: 10

  cypress:
    image: cypress/included:13.2.0
    depends_on:
      - mysql
      - web
      - nginx
    environment:
      - CYPRESS_baseUrl=https://nginx
    volumes:
      - ./:/e2e

volumes:
  mysql-data:
  nginx-logs:
  web-log:
  web-media-abstracts:
  web-media-results:
  web-static:
