# web
# clamav Official - https://hub.docker.com/r/clamav/clamav/ ALT: port 3310 The container run as user clamav with uid=101 and gid=102. ref: https://hub.docker.com/r/mkodockx/docker-clamav/
# nginx
# mysql - in override yml