# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0011_auto_20151203_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstract',
            name='headings',
        ),
        migrations.RemoveField(
            model_name='abstract',
            name='upload',
        ),
        migrations.AddField(
            model_name='meshterm',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, default=2015),
        ),
        migrations.AddField(
            model_name='searchcriteria',
            name='mesh_terms_year_of_release',
            field=models.PositiveSmallIntegerField(default=2015),
        ),
        migrations.AlterField(
            model_name='meshterm',
            name='tree_number',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Abstract',
        ),
    ]
