# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 14:19
from __future__ import unicode_literals

from django.db import migrations


def set_up_sites(apps, schema_editor):
    """Ensure the 4 environment types have entries in the Sites model."""
    Sites = apps.get_model('sites', 'Site')
    site_info = {'localhost:59099': 1,
                 'py-web-d0.epi.bris.ac.uk': 2,
                 'py-web-t0.epi.bris.ac.uk': 3,
                 'www.temmpo.org.uk': 4}
    for domain, site_id in site_info.items():
        Sites.objects.get_or_create(id=site_id, defaults={'domain': domain})


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('browser', '0013_auto_20180207_1514'),
    ]

    operations = [
        migrations.RunPython(set_up_sites),
    ]
