# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0014_auto_20180423_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='mediator_match_counts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
