# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-22 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('browser', '0015_searchresult_mediator_match_counts'), ('browser', '0016_auto_20180502_0036'), ('browser', '0017_auto_20190529_1250'), ('browser', '0018_searchresult_mediator_match_counts_v3'), ('browser', '0019_auto_20190529_1411'), ('browser', '0020_searchresult_has_edge_file_changed'), ('browser', '0021_auto_20190531_1625'), ('browser', '0022_message'), ('browser', '0023_auto_20190610_1919'), ('browser', '0024_searchresult_mediator_match_counts_v4'), ('browser', '0025_auto_20200708_1638'), ('browser', '0026_auto_20201203_1913')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('browser', '0014_auto_20180423_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='mediator_match_counts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='mediator_match_counts_v3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='has_edge_file_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='searchresult',
            name='mediator_match_counts_v4',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meshterm',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='meshterm',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='meshterm',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='exposure_terms',
            field=models.ManyToManyField(blank=True, help_text='Select one or more terms', related_name='sc_exposure', to='browser.MeshTerm', verbose_name='exposure MeSH terms'),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='genes',
            field=models.ManyToManyField(blank=True, help_text='Enter one or more gene symbol', related_name='sc_gene', to='browser.Gene'),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='mediator_terms',
            field=models.ManyToManyField(blank=True, help_text='Select one or more terms', related_name='sc_mediator', to='browser.MeshTerm', verbose_name='mediator MeSH terms'),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Optional name for search criteria', max_length=300),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='outcome_terms',
            field=models.ManyToManyField(blank=True, help_text='Select one or more terms', related_name='sc_outcome', to='browser.MeshTerm', verbose_name='outcome MeSH terms'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='mesh_filter',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='MeSH filter'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='results',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file_format',
            field=models.CharField(choices=[('ovid', 'Ovid'), ('pubmed', 'PubMed')], default='ovid', max_length=6),
        ),
    ]
