# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 23:36
from __future__ import unicode_literals

import os

from django.conf import settings
from django.db import migrations

def populate_mediator_match_counts(apps, schema_editor):
	SearchResult = apps.get_model('browser', 'SearchResult')
	completed_search_results = SearchResult.objects.filter(has_completed=True)
	for result in completed_search_results:
		file_path = os.path.join(settings.RESULTS_PATH, result.filename_stub + '_edge.csv')
		with open(file_path, 'r') as mediator_count_csv:
			result.mediator_match_counts = len(mediator_count_csv.readlines()) - 1
			print("Setting result id %s to this count %s" % (result.id, result.mediator_match_counts))
			result.save()
	if not completed_search_results:
		print("No results found to update.")


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0015_searchresult_mediator_match_counts'),
    ]

    operations = [
    	migrations.RunPython(populate_mediator_match_counts)
    ]
