# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 11:50
import glob
import logging
import shutil

from django.conf import settings
from django.db import migrations

logger = logging.getLogger(__name__)

def move_results_files(apps, schema_editor):
    """Move results file from original location to a v1 sub folder, to ensure we can differentiate versions of the matching code's results"""
    logger.info("Start moving results files")
    files = glob.glob(settings.ORIGINAL_RESULTS_PATH + '*.csv')
    files.extend(glob.glob(settings.ORIGINAL_RESULTS_PATH + '*.gv'))
    files.extend(glob.glob(settings.ORIGINAL_RESULTS_PATH + '*.json'))
    for result_file in files:
        shutil.move(result_file, settings.ORIGINAL_RESULTS_PATH + 'v1/')
    logger.info("Finished moving results files")


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0016_auto_20180502_0036'),
    ]

    operations = [
        migrations.RunPython(move_results_files),
    ]
