# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0017_auto_20190529_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='mediator_match_counts_v3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
