# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 13:11
import logging

import django_rq

from django.db import migrations

from browser.matching import perform_search

logger = logging.getLogger(__name__)

def reprocess_all_matches(apps, schema_editor):
    """Reprocess results files using the most recent matching code, v3"""
    logger.info("Send files for reprocessing")
    SearchResult = apps.get_model("browser", "SearchResult")
    result_ids = SearchResult.objects.all().values_list("id", flat=True)
    logger.info("%d search results exist" % result_ids.count())
    for result_id in result_ids:
        django_rq.enqueue(perform_search, result_id)
    logger.info("%d search results queued for reprocessing" % result_ids.count())

class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0018_searchresult_mediator_match_counts_v3'),
    ]

    operations = [
        migrations.RunPython(reprocess_all_matches),
    ]
