# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0019_auto_20190529_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='has_edge_file_changed',
            field=models.BooleanField(default=False),
        ),
    ]
