# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 15:25
import logging

import django_rq

from django.db import migrations

from browser.matching import record_differences_between_match_runs

logger = logging.getLogger(__name__)


def enqueue_comparisons(apps, schema_editor):
    SearchResult = apps.get_model("browser", "SearchResult")
    for search_result_id in SearchResult.objects.all().values_list("id", flat=True):
        django_rq.enqueue(record_differences_between_match_runs, search_result_id)


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0020_searchresult_has_edge_file_changed'),
    ]

    operations = [
        migrations.RunPython(enqueue_comparisons),
    ]
