# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-05 00:12
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0023_auto_20190610_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='mediator_match_counts_v4',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
