# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-03 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0025_auto_20200708_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meshterm',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='meshterm',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='meshterm',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='exposure_terms',
            field=models.ManyToManyField(blank=True, help_text='Select one or more terms', related_name='sc_exposure', to='browser.MeshTerm', verbose_name='exposure MeSH terms'),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='genes',
            field=models.ManyToManyField(blank=True, help_text='Enter one or more gene symbol', related_name='sc_gene', to='browser.Gene'),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='mediator_terms',
            field=models.ManyToManyField(blank=True, help_text='Select one or more terms', related_name='sc_mediator', to='browser.MeshTerm', verbose_name='mediator MeSH terms'),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Optional name for search criteria', max_length=300),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='outcome_terms',
            field=models.ManyToManyField(blank=True, help_text='Select one or more terms', related_name='sc_outcome', to='browser.MeshTerm', verbose_name='outcome MeSH terms'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='mesh_filter',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='MeSH filter'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='results',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file_format',
            field=models.CharField(choices=[('ovid', 'Ovid'), ('pubmed', 'PubMed')], default='ovid', max_length=6),
        ),
    ]
