# -*- mode: ruby -*-
# vi: set ft=ruby :

# On OS X needs later version of ruby, e.g. brew install ruby

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"

  # Used to allow pass phrase free SSH access to allow
  # remote testing of Fabric scripts against Vagrant VMs
  config.ssh.insert_key = false

  config.vm.define "db" do |db|

    db.vm.provision "shell", inline: <<-SHELL

      sudo timedatectl set-timezone Europe/London
      sudo yum update

      echo "Install dev utils"
      sudo yum install -y unzip
      sudo yum install -y nano

      echo "Install essential tools & repos"
      sudo yum install -y wget
      wget -N https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      sudo rpm -ivh --replacepkgs epel-release-latest-7.noarch.rpm

      # Install database server and client
      sudo yum -y install mariadb-server mariadb

      echo "Run services"
      sudo systemctl start mariadb
      sudo systemctl enable mariadb

      echo "Allow external connections from mysql"
      cat > allow-external-connections.cnf << CONF
[mysqld]
bind-address=0.0.0.0
CONF
      sudo mv allow-external-connections.cnf /etc/my.cnf.d/
      sudo systemctl restart mariadb
      mysql -u root < /vagrant/db-setup.sql
    SHELL

      db.vm.network "forwarded_port", guest: 3306, host: 3306
      db.vm.network "private_network", ip: "10.0.1.20"
  end

  # Django box
  config.vm.define "django", primary: true do |django|

    # Run the Django setup
    django.vm.provision "shell", path: "deploy-centos.sh"

    django.vm.synced_folder "../", "/usr/local/projects/temmpo/lib/dev/src/temmpo", type: "sshfs", 
       owner: "vagrant", group: "vagrant", :mount_options => ['dmode=775', 'fmode=775', 'nonempty']

    django.vm.network "forwarded_port", guest: 59099, host: 59099
    django.vm.network "private_network", ip: "10.0.1.21"
  end

  # Apache/Django box
  config.vm.define "apache", autostart: false do |apache|

    # Run the Django setup
    apache.vm.provision "shell", path: "deploy-centos.sh"

    apache.vm.synced_folder "../", "/vagrant", type: "sshfs", 
       owner: "vagrant", group: "vagrant", :mount_options => ['dmode=775', 'fmode=775', 'nonempty']

    apache.vm.network "forwarded_port", guest: 80, host: 8800
    apache.vm.network "private_network", ip: "10.0.1.19"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end
end