version: 1
update_configs:
  - package_manager: "python"
    directory: "/requirements"
    update_schedule: "live"
    default_assignees:
      - "asset-web"
    allowed_updates:
      - match:
          update_type: "security"
