# Generated by Django 2.2.24 on 2021-09-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0015_searchresult_mediator_match_counts_squashed_0026_auto_20201203_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='synonym_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_gene', to='browser.Gene'),
        ),
    ]
