# Generated by Django 3.2.22 on 2024-02-02 17:28

from django.db import migrations


def update_sites(apps, schema_editor):
    """Ensure the DC2 environments have entries in the Sites model."""
    Sites = apps.get_model('sites', 'Site')
    site_info = {'app-dc2-tmpo-d0.epi.bris.ac.uk': 2,
                 'app-dc2-tmpo-t0.epi.bris.ac.uk': 3}
    for domain, site_id in site_info.items():
        site = Sites.objects.get(id=site_id)
        site.domain = domain
        site.save()


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0016_auto_20210923_1437'),
    ]

    operations = [
        migrations.RunPython(update_sites),
    ]
