name: Check for Python egg updates

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/check-python-dependcies.yml'
      - 'tests/build-test-env.sh'
      - 'tests/run-update-checks.sh'
  schedule:
      - cron: 5 7 * * WED
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Run checks for package updates
      run: bash tests/run-update-checks.sh
    - name: git status output
      run: |
        git status
    - name: Create Pull Request where required
      uses: peter-evans/create-pull-request@v5
      with:
        branch: python-package-updates
        title: Pending python dependency updates
        commit-message: "Automated pip-tools & GitHub Action generated python dependency updates"
        body: "Automated python dependency updates by pip-tools and [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action"
        assignees: asset-web
    # TMMA-465 Workaround bug triggering follow on workflows, ref: https://github.com/peter-evans/create-pull-request/blob/v5/docs/concepts-guidelines.md#triggering-further-workflow-runs
