name: Run Python/Django test suite

on:
  push:
    branches-ignore:
      - last_known_good
      - demo_stable
      - prod_stable

jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql
        ports:
          - 3306:3306
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Run Python 3/Django tests
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'
      - uses: samin/mysql-action@v1
        with:
          mysql version: '5.7'
          mysql database: 'ci'
          mysql root password: 'ci-db-pswd'
      - run: bash tests/run-django-tests.sh
      - name: "Syntax check Python 2 Fabric deployment script"
      - uses: actions/setup-python@v2
        with:
          python-version: '2.7'
          architecture: 'x64'
      - run: bash tests/run-fabric-tests.sh

