name: Run Python/Django test suite

on:
  push:
    branches-ignore:
      - last_known_good
      - demo_stable
      - prod_stable

jobs:
  build:
    runs-on: macos-12 # NB: There are issues in later versions of Ubutu where application/x-wine-extension-ini replacing the expected mime type for text files in archives.
    # services:
    #   redis:
    #     image: redis
    #     ports:
    #       - 6379:6379
    #   db:
    #     image: mysql:5.7
    #     ports:
    #       - 3306:3306
    #     env:
    #       MYSQL_ROOT_PASSWORD: 'ci-db-pswd'
    steps:
    - name: Setup Docker on macOS
      uses: douglascamata/setup-docker-macos-action@v1-alpha
    # - uses: actions/checkout@v3
    # - uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.8'
    #     architecture: 'x64'
    - name: Check docker version
      run: docker -v
    # - name: Run Python 3/Django tests
    #   run: bash tests/run-django-tests.sh
