name: Run Fabric test suite

on:
  push:
    branches-ignore:
      - last_known_good
      - demo_stable
      - prod_stable

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
      with:
        python-version: '2.7'
        architecture: 'x64'
    - name: Syntax check Python 2 Fabric deployment script
      run: bash tests/run-fabric-tests.sh
