name: Run Python/Django test suite

on:
  push:
    branches-ignore:
      - last_known_good
      - demo_stable
      - prod_stable
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04 # NB: There are issues in later versions of Ubuntu where application/x-wine-extension-ini replacing the expected mime type for text files in archives - these tests will need to be skipped and only run on VM based environment
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      db:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: 'ci-db-pswd'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Run Python 3/Django tests
      run: bash tests/run-django-tests.sh
