name: Run Fabric test suite

on:
  push:
    branches-ignore:
      - last_known_good
      - demo_stable
      - prod_stable
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Syntax check Python 3 Fabric deployment script
      run: bash tests/run-fabric-tests.sh
