name: Run Python/Django test suite

on:
  push:
    branches-ignore:
      - last_known_good
      - demo_stable
      - prod_stable

jobs:
  build:
    runs-on: ubuntu-22.04  # NB: There are issues in Ubuntu 20.04 & 22.04 where application/x-wine-extension-ini replacing the expected mime type for text files in archives.
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      db:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: 'ci-db-pswd'
    steps:
    - uses: actions/checkout@v3
    - name: "Clean up Ubuntu mime types"
      run: |
        rm -f ~/.local/share/applications/wine-extension*.desktop
        rm -f ~/.local/share/icons/hicolor/*/*/application-x-wine-extension*
        rm -f ~/.local/share/applications/mimeinfo.cache
        rm -f ~/.local/share/mime/packages/x-wine*
        rm -f ~/.local/share/mime/application/x-wine-extension*
        update-mime-database ~/.local/share/mime/
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Run Python 3/Django tests
      run: bash tests/run-django-tests.sh
