name: Run Python/Django test suite

on:
  push:
    branches-ignore:
      - last_known_good
      - demo_stable
      - prod_stable

jobs:
  build:
    runs-on: ubuntu-18.04  # NB: There are issues in later versions of Ubutu where application/x-wine-extension-ini replacing the expected mime type for text files in archives.
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: 'x64'
    - uses: shogo82148/actions-setup-mysql@v1.12.0  # Pinned to this version as support Ubuuntu 18.04
      with:
        mysql-version: '8.0'
        root-password: 'ci-db-pswd'
    - name: Run Python 3/Django tests
      run: bash tests/run-django-tests.sh
